spring.jpa.hibernate.ddl-auto=update
# spring.sql.init.mode=always
# spring.sql.init.schema-locations=classpath:schema.sql
# spring.sql.init.data-locations=classpath:data.sql

spring.sql.init.platform=postgresql

spring.datasource.url=jdbc:postgresql://localhost:5432/mondatelier
spring.datasource.username=mondatelier
spring.datasource.password=mondatelier

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always

security.jwt.secret-key=bd14230623ed0ca1d61d3cd737317e9b11a4f031d8a231eaa736b77b780ddbfa
security.jwt.expiration-time=8640000

app.frontend.url=http://localhost:5174

app.upload.dir=../uploads
