# data source
spring.datasource.url=jdbc:postgresql://db.yivnlhzedywclqhvsfmn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1c09VOm9ZlnELH5e
spring.datasource.driver-class-name=org.postgresql.Driver

# security
security.jwt.secret-key=bd14230623ed0ca1d61d3cd737317e9b11a4f031d8a231eaa736b77b780ddbfa

# uploads
app.upload.dir=../uploads
