# Data source for tests
spring.datasource.url=jdbc:postgresql://localhost:5432/mondateliertestdb
spring.datasource.username=mondatelier
spring.datasource.password=mondatelier
spring.datasource.driver-class-name=org.postgresql.Driver
