spring.application.name=mondatelier

#time zone
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# data source
spring.datasource.url=jdbc:postgresql://localhost:5432/mondatelier
spring.datasource.username=mondatelier
spring.datasource.password=mondatelier
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

#sql
spring.sql.init.platform=postgresql

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# security
security.jwt.secret-key=bd14230623ed0ca1d61d3cd737317e9b11a4f031d8a231eaa736b77b780ddbfa
security.jwt.expiration-time=3600000
security.jwt.refresh-expiration-time=604800000

#file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# frontend
app.frontend.url=
app.upload.dir=/Users/kursat/Documents/Code\ Base/Mondatelier/uploads
app.community.feed-limit=15
app.community.comment-limit=10