spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

app.frontend.url=${FRONTEND_URL}
app.upload.dir=${UPLOAD_DIR}
security.jwt.cookie-secure=true

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
