spring.datasource.url=jdbc:postgresql://localhost:5432/mondatelier
spring.datasource.username=mondatelier
spring.datasource.password=mondatelier

# jpa
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# error handling
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always

#security
security.jwt.secret-key=bd14230623ed0ca1d61d3cd737317e9b11a4f031d8a231eaa736b77b780ddbfa
security.jwt.refresh-expiration-time=9000000

#sql
spring.sql.init.platform=postgresql

# frontend
app.frontend.url=http://localhost:5173
app.upload.dir=../uploads

