spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mondatelier}
spring.datasource.username=${DB_USERNAME:mondatelier}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

spring.sql.init.platform=postgresql
